abbr -a c 'clear'
abbr -a g 'git status -s'
abbr -a ga 'git add'
abbr -a gA 'git add -A'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -D'
abbr -a gch 'git checkout'
abbr -a gchb 'git checkout -b'
abbr -a gchm 'git checkout master'
abbr -a gd 'git diff'
abbr -a gdc 'git diff --cached'
abbr -a gk 'git commit -m'
abbr -a gka 'git commit --amend'
abbr -a gl 'git log'
abbr -a gpl 'git pull'
abbr -a gplr 'git pull -r'
abbr -a gplro 'git pull -r origin'
abbr -a gplrom 'git pull -r origin master'
abbr -a gplru 'git pull -r upstream'
abbr -a gplo 'git pull origin'
abbr -a gplom 'git pull origin master'
abbr -a gplu 'git pull upstream'
abbr -a gps 'git push'
abbr -a gpsf 'git push -f'
abbr -a gr 'git reset'
abbr -a gsh 'git stash'
abbr -a gsha 'git stash apply'
abbr -a n 'npm'
abbr -a ni 'npm install'
abbr -a nis 'npm install --save'
abbr -a nisd 'npm install --save-dev'